### ISSUE TITLE
Non-unit stride inverts lower bound in the SCoP representation

### ISSUE THREAD

**Issue by ftynse** [periscop/clan#11]
The original code
```c
#pragma scop
for (i = 1; i < 42; i++) {
  S1(i);
}
#pragma endscop
```
generates a proper constraint in the matrix representation: `i - 1 >= 0`.

while introducing a non-unit stride makes it somehow inverted
```c
#pragma scop
for (i = 1; i < 42; i += 2) {
  S1(i);
}
#pragma endscop
```
results in the constraint `i + 1 >= 0`, which does not correspond to the iteration domain at hand.  Apparently, inversion is made to support the creation of the local dimension as `i + 1 = 2*l1`

**Comment by Ced** [comment]
Solved. A stupid one character bug introduced nearly 5 years ago... And killed in 5 hours after several unsuccessful attempts. Bye buggy.
