### ISSUE TITLE
max inside a statement body leads to extraction failure

### ISSUE THREAD

**Issue by bondhugula** [periscop/clan#14]
I was expecting max to be treated as a pure function here. However, I get an extraction failure. Renaming max to something else makes it work. A similar problem with min.

$ cat test/max.c
#pragma scop
for (j=0; j<N; j++) {
    c = max(a, b);
}
#pragma endscop

$ clan/clan -v
clan 0.8.0        The Chunky Loop Analyzer
$ clan/clan test/max.c
[Clan] Info: parsing file #1 (test/max.c)
[Clan] Error: syntax error at line 3, column 11.
    c = max(a, b);
       ~~~^
# NULL scop

**Comment by ftynse** [comment]
Apparently, Clan lexer treats max/min as a keyword that is later interpreted in affine conditions and this keyword is not integrated properly into the rest of C statement grammar.

**Comment by ftynse** [comment]
Check if https://github.com/ftynse/clan/commit/42a7d0c556f54a4eb40b0b9bc3fcd9f86ae8dd90 helps...

**Comment by ftynse** [comment]
Fixed by 42a7d0c556f54a4eb40b0b9bc3fcd9f86ae8dd90.
Closed.
