### ISSUE TITLE
Cannot build Clan

### ISSUE THREAD

**Issue by thiagotei** [periscop/clan#19]
Error during the build. 

```
./autogen.sh
./configure --with-osl=system --with-osl-exec-prefix=/home/thiago/Documents/periscop/install  --with-osl-prefix=/home/thiago/Documents/periscop/install --prefix=/home/thiago/Documents/periscop/install 
make V=1
```

Error:
```
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -g -O2   -o clan source/clan-clan.o -losl  libclan.la -losl 
libtool: link: gcc -g -O2 -o .libs/clan source/clan-clan.o  ./.libs/libclan.so -losl -Wl,-rpath -Wl,/home/thiago/Documents/periscop/install/lib
/usr/bin/ld: cannot find -losl
```

**Comment by Syllo** [comment]
Hi,

Could you please indicate on which distribution you encountered this error along with the output of  ```gcc --version``` and  ```libtool --version```
We were not able to reproduce the same behavior on our systems.

The following command should fix the problem temporarily:
```{.bash}
make LDFLAGS="$LDFLAGS -L/home/thiago/Documents/periscop/install/lib"
```

**Comment by thiagotei** [comment]
Weirdly I could not reproduce the error, from the beginning. I'm not sure what happened. One
thing that I remember was to recompile osl with autotools instead of cmake.
Thanks anyway.
